### ISSUE TITLE
`Extrinsics::is_signed` method

### ISSUE THREAD

**Issue by muraca** [Off-Narrative-Labs/Tuxedo#109]
https://github.com/Off-Narrative-Labs/Tuxedo/blob/f84150ca96eafb21c196b8a4f8fc94e68d6a6f32/tuxedo-core/src/types.rs#L105

In method `Extrinsics::is_signed`, what are the consequences of returning `Some(false)` vs `None` (default)?
This research was made on Polkadot SDK at [a56fd32](https://github.com/paritytech/polkadot-sdk/commit/a56fd32e0affbe9cb61abb5ee3ec0a0bd15f5bf0).

Generally speaking, `None` should be used when no information about the signature is available, so the `Some(false)` should be preferred in this case.

All the FRAME-related usages are skipped, since Tuxedo is not designed to work on FRAME.

## Inherents procedural macro

Inherents are placed in a block before any other extrinsic. This method is used to break out of a loop that iterates on the extrinsics of a block, as soon as a signed extrinsic is found. 
Here, when `None`, a transaction is assumed to be unsigned, and is later on checked using `Pallet::is_inherent`, so there’s no difference if we return `None` or `Some(false)`.

## Cumulus validate block implementation

This is another case where the method is used to look for inherents. In contrast to the previous, here a `None` result will be considered as `true`. 

## Substrate client transaction pool

Method `BasicPool::handle_enactment`:

> Handles enactment and retraction of blocks, prunes stale transactions (that have already been enacted) and resubmits transactions that were retracted.

We can find only one usage, where a `None` result is considered to be `true`. 
This allows explicitly signed transactions, or transactions where the pool doesn’t know wether the transaction is signed or not, to be resubmitted when the block that contains it is pruned.

I went back through multiple refactorings of the code, and I found out this was initially set up to avoid resubmitting inherents in [Substrate PR 3660](https://github.com/paritytech/substrate/pull/3660). The behavior was different, since it initially defaulted the value to false, and it was changed later on in [Substrate PR 4740](https://github.com/paritytech/substrate/pull/4740).

## Conclusions

At the moment I think it should be None, but I have to figure out why an extrinsic is not signed in Tuxedo. @JoshOrndorff any explanation?

**Comment by JoshOrndorff** [comment]
Thanks for the detailed research. This is extremely helpful. I think we can soon decide how to proceed.

## Why are UTXO Transactions unsigned?

First, notice that this is UTXO thing, not just a Tuxedo thing. UTXO transactions are never signed in their entirety. Although they may contain pieces of signed data, and indeed they often do. Let's look at the structure of a transaction in the UTXO and Account models.

Slightly simplified version of Tuxedo's [Transaction Type](https://off-narrative-labs.github.io/Tuxedo/tuxedo_core/types/struct.Transaction.html)
```rust
pub struct Transaction {
    pub inputs: Vec<Input>,
    /// Existing state to be read, but not consumed, from storage
    pub peeks: Vec<OutputRef>,
    /// New state to be placed into storage
    pub outputs: Vec<Output>,
    /// Piece of constraint checking logic to determine whether this transaction is valid
    pub checker: ConstraintChecker,
}
```

Slightly Simplified version of FRAME's [UncheckedExtrinsc Type](https://paritytech.github.io/polkadot-sdk/master/sp_runtime/generic/struct.UncheckedExtrinsic.html)
```rust
pub struct UncheckedExtrinsic {
    pub signature: Option<(Address, Signature)>,
    pub function: Call,
}
```

In account-based systems, there is a field for a signature directly on the transaction, and therefore, signed transactions (which is the vast majority of them) are associated with a particular sending account.

UTXOs work differently. In UTXOs, each individual utxo (eg a coin) has some rules for when it can be spent. The rules for many coins are that the require a signature from their owner, but they could also be free, or unspendable, or require the answer to a riddle to be spent.

Here's a motivating example of why the UTXO model does this. Imagine Alice and Bob want to pool their funds to buy a radio transmitter and antenna. In UTXO,s we could have a single transaction that consumes several coins from Alice, and several coins from Bob, and gives outputs to the radio vendor, and the antenna vendor. One single transaction. Alice signs her own coins, and bob signs his own coins, but nobody signs the entire transaction.

In the Accounts model. This would take a transaction for pooling the money, a second one to buy the radio, and a third to buy the antenna. And more if they wanted some trustless way to handle the pooled money.

## The proc macro is part of FRAME

The [proc macro](https://github.com/paritytech/polkadot-sdk/blob/a56fd32e0affbe9cb61abb5ee3ec0a0bd15f5bf0/substrate/frame/support/procedural/src/construct_runtime/expand/inherent.rs) you discovered is actually part of FRAME also, so we don't need to consider it either. It is part of `construct_runtime!` which is part of `frame-support`.

## What is your conclusion?

In the beginning you say

> so the `Some(false)` should be preferred in this case.

But at the end you say

> At the moment I think it should be None

Actually the main thing I took away from your research is that this is part of a complicated history involving the distinction between inherents and unsigned transactions in FRAME.

Do you think this mapping is correct? (@kianenigma maybe you know?)

`Some(false)` => inherent
`None` => unsigned user-submitted transaction
`Some(true) => user signed transaction

If this is the case, I think we should use `Some(false)` for inherents and `None` for normal UTXO transactions.

## Related to my `is_inherent` function

It's very fortunate that you dug in on this right now because it is related to my work in #100. I introduced a `is_inherent` function over there, and I hadn't realized how closely related it is to this `is_signed` function.

I'm starting to think we should abuse the `is_signed` method to actually tell whether the transaction in an inherent. It seems like this is what the transaction pool and the cumulus validate block both want to know.

## Regarding Transaction Ordering

FYI FRAME enforces that inherents come first in a block. Substrate itself does not enforce this, and allows them to come anywhere. So while Substrate is very general, the runtime framework can impose a more strict convention.

What I'm planning in Tuxedo is similar to FRAME except that we will allow inherents at both the beginning and the end of the block. Each inherent will belong either at the beginning or the end and Tuxedo will enforce that they are there.

**Comment by JoshOrndorff** [comment]
So basically what I'm proposing is something like the following. I think it makes sense to put it in after #100 goes in because that's when the `is_inherent` function goes in.

```rust
impl Extrinsic for TuxedoTransaction {
  // --snip--

  // The signature on this function is not the best. Ultimately it is
  // trying to distinguish between three potential types of transactions:
  // 1. Signed user transactions: `Some(true)`
  // 2. Unsigned user transactions: `None`
  // 3. Unsigned inherents: `Some(false)`
  //
  // In Substrate generally, and also in FRAME, all three of these could exist.
  // But in Tuxedo we will never have signed user transactions, and therefore
  // will never return `Some(true)`.
  //
  // Perhaps a dedicated enum makes more sense as the return type?
  // That would be a Substrate PR after this is more tried and true.
  fn is_signed(&self) -> Option(bool) {
    if self.checker.is_inherent() {
      Some(false)
    } else {
      None
    }
  }
}
```

**Comment by muraca** [comment]
Thanks for explaining why transactions on Tuxedo are considered to be unsigned, even if they contain signatures.
Quick clarification: in the beginning I say 
> Generally speaking, None should be used when no information about the signature is available, so the Some(false) should be preferred in this case.

This is because we do have information about the transaction signature: there's none. 
However, considering how Substrate uses this information, my opinion is that the method should be used based on `is_inherent` as well.

**Comment by JoshOrndorff** [comment]
I sketched this out in 4a8cdabfe058ce7f4f46f759d949f49b98ae455b as part of #100

**Comment by kianenigma** [comment]
(haven't had the time to read the whole context yet, but seemingly very related to https://github.com/paritytech/polkadot-sdk/pull/2280#discussion_r1472875596 -- TLDR I kinda think this `trait Extrinsic` is broken).
